ignore:
  - vulnerability: CVE-2021-27498
    package:
      type: npm
      name: opener
  - vulnerability: CVE-2021-27500
    package:
      type: npm
      name: opener
  - vulnerability: CVE-2021-27478
    package:
      type: npm
      name: opener
  - vulnerability: CVE-2021-27482
    package:
      type: npm
      name: opener                  
# All below are node.js 14/16 issues
  - vulnerability: GHSA-93q8-gq69-wqmw
    package:
      type: npm
      name: ansi-regex
  - vulnerability: CVE-2021-3807
    package:
      type: npm
      name: ansi-regex
  - vulnerability: CVE-2015-0903
    package:
      type: npm
      name: editor
  - vulnerability: CVE-2014-1936
    package:
      type: npm
      name: rc
  - vulnerability: CVE-2020-17753
    package:
      type: npm
      name: rc
  - vulnerability: CVE-2021-29940
    package:
      type: npm
      name: through
  - vulnerability: GHSA-xvch-5gv4-984h
    package:
      type: npm
      name: minimist
  - vulnerability: CVE-2021-44906
    package:
      type: npm
      name: minimist
