ignore:
  - vulnerability: GHSA-3v7f-55p6-f55p
    reason: "Node: 22,24: npm picomatch"
  - vulnerability: CVE-2025-60876
    reason: "Node: 22,24: BusyBox"
  - vulnerability: GHSA-c2c7-rcm5-vvqj
    reason: "Node: 22,24: npm picomatch"
  - vulnerability: GHSA-f886-m6hf-6m8v
    reason: "Node: 22,24: npm brace-expansion"
  - vulnerability: GHSA-v2v4-37r5-5v8g
    reason: "Node: 22,24: npm ip-address"
  - vulnerability: GHSA-jxxr-4gwj-5jf2
    reason: "Node: 24: npm brace-expansion"
  - vulnerability: GHSA-vmf3-w455-68vh
    reason: "Node: 22,24: npm tar"
  - vulnerability: GHSA-vxpw-j846-p89q
    reason: "Node: 24: undici"
  - vulnerability: GHSA-p88m-4jfj-68fv
    reason: "Node: 24: undici"
  
