ignore:
  - vulnerability: GHSA-3xgq-45jj-v275-cross-spawn
  - vulnerability: CVE-2024-21538
    package:
      type: npm
      name: cross-spawn
  - vulnerability:  CVE-2021-43616
    package:
      type: npm
      name: npm
