name: NIGHTLY-SCAN

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  get-matrix-values:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-var.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - id: set-var
        run: |
          echo 'image<<EOF' >> $GITHUB_OUTPUT
          cat ./image-matrix.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  
  anchore-scan:
    runs-on: ubuntu-latest
    needs:  get-matrix-values
    strategy:
      matrix:
        image: ${{fromJSON(needs.get-matrix-values.outputs.image)}}
    steps:
      - uses: actions/checkout@v3
      - name: Set job environment variables
        run:  cat JOB.env >> $GITHUB_ENV
      - name: Scan Node.js docker image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: defradigital/${{env.IMAGE_NAME}}:${{env.DEFRA_VERSION}}-node${{matrix.image.runTimeVersion}}
          fail-build: true
          severity-cutoff: "medium"

      - name: Upload Anchore Grype SARIF report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports-node-${{ matrix.image.runtimeVersion }}
          path: ${{ steps.scan.outputs.sarif }}          
