name: NIGHTLY-SCAN

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  get-matrix-values:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-var.outputs.image }}
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          content=`cat ./image-matrix.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=image::$content"
  
  anchore-scan:
    runs-on: ubuntu-latest
    needs:  get-matrix-values
    strategy:
      matrix:
        image: ${{fromJSON(needs.get-matrix-values.outputs.image)}}
    steps:
      - uses: actions/checkout@v2
      - name: Set job environment variables
        run:  cat JOB.env >> $GITHUB_ENV
      - name: Scan Node.js docker image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: defradigital/$IMAGE_NAME:$DEFRA_VERSION-node${{matrix.image.runTimeVersion}}
          fail-build: true
          severity-cutoff: "medium"
      - name: Archive anchore report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports-node-${{ matrix.image.runtimeVersion }}
          path: ${{ steps.scan.outputs.sarif }}          
