name: NIGHTLY-SCAN

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  get-matrix-values:
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.set-var.outputs.include }}
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          content=`cat ./matrix-include.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=include::$content"
  
  anchore-scan:
    runs-on: ubuntu-latest
    needs:  get-matrix-values
    strategy:
      matrix:
        include: ${{fromJSON(needs.get-matrix-values.outputs.include)}}
    steps:
      - uses: actions/checkout@v2
      - name: Set job environment variables
        run:  cat JOB.env >> $GITHUB_ENV
      - name: Scan Node.js docker image
        uses: anchore/scan-action@v1
        with:
          image-reference: defradigital/${{env.IMAGE_NAME}}:${{env.DEFRA_VERSION}}-node${{matrix.runTimeVersion}}
          fail-build: true
          custom-policy-path: ./anchore-policy.json
          include-app-packages: true

      - name: Archive anchore report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports-node-${{ matrix.runtimeVersion }}
          path: anchore-reports
