name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:
  scan-node14:
    env:
      NODE_VERSION: 14.15.0
      ALPINE_VERSION: alpine3.12
      DEFRA_VERSION: 1.2.3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --no-cache --build-arg DEFRA_VERSION=$DEFRA_VERSION --build-arg BASE_VERSION=$NODE_VERSION-$ALPINE_VERSION --tag defradigital/node:$DEFRA_VERSION-node$NODE_VERSION
      - uses: anchore/scan-action@v1
        with:
          image-reference: defradigital/node:${{ env.DEFRA_VERSION }}-node${{ env.NODE_VERSION }}
          fail-build: true
          custom-policy-path: ./anchore-policy.json
          include-app-packages: true

      - name: Archive anchore report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports-node14-pr
          path: anchore-reports

